// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9IYPD_kNv_dyz1xpSPTGS4rhlQ7ba8rE',
    appId: '1:391579690300:android:55c7f8c8166d2d8062aa39',
    messagingSenderId: '391579690300',
    projectId: 'luis-mx',
    databaseURL: 'https://luis-mx-default-rtdb.firebaseio.com',
    storageBucket: 'luis-mx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk3r6FAAo_TMVUtxBFDkcubc7ZCLdz_w8',
    appId: '1:391579690300:ios:ba7fa541fd8bc1cc62aa39',
    messagingSenderId: '391579690300',
    projectId: 'luis-mx',
    databaseURL: 'https://luis-mx-default-rtdb.firebaseio.com',
    storageBucket: 'luis-mx.appspot.com',
    iosClientId: '391579690300-dstgh4c6kob1hp589vh8gh6ckdum3v6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.kueskiApp',
  );
}
